= OAuth 2.0
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_devguide_protocols_oauth2_overview.html
:page-folder: am/dev-guide/protocols/oauth2
:page-layout: am

== Overview

link:https://tools.ietf.org/html/rfc6749[OAuth 2.0] is the industry-standard protocol for authorization providing specific authorization flows for web applications, desktop applications, mobile phones and home devices.

OAuth 2.0 specifies standard endpoints to interact with the resource owner (or the client when is acting on its own behalf) to grant/introspect/revoke tokens used to access protected resources.

You can find OAuth 2.0 protocol endpoints exposed by AM in the online API reference or the OpenAPI specification:

* link:/am/current/oauth2/index.html[OAuth 2.0 API Console, window="_blank"] - link:/am/current/oauth2/swagger.yml[OpenAPI spec, window="_blank"]

== Roles

OAuth 2.0 defines four roles:

* `resource owner`
      An entity capable of granting access to a protected resource.
      When the resource owner is a person, it is referred to as an
      end user.

* `resource server`
      The server hosting the protected resources, capable of accepting
      and responding to protected resource requests using access tokens.

* `client`
      An application making protected resource requests on behalf of the
      resource owner and with its authorization.  The term "client" does
      not imply any particular implementation characteristics (e.g.,
      whether the application executes on a server, a desktop, or other
      devices).

* `authorization server`
      The server issuing access tokens to the client after successfully
      authenticating the resource owner and obtaining authorization.

== Grant types

An authorization grant is a flow used by the client to obtain an access token.

The specification defines four grant types :

- link:/am/current/am_devguide_protocols_oauth2_overview.html#authorization_code[Authorization code]
- link:/am/current/am_devguide_protocols_oauth2_overview.html#implicit[Implicit]
- link:/am/current/am_devguide_protocols_oauth2_overview.html#resource_owner_password_credentials[Resource owner password credentials]
- link:/am/current/am_devguide_protocols_oauth2_overview.html#client_credentials[Client credentials]

NOTE: OAuth 2.0 also supports the use of link:/am/current/am_devguide_protocols_oauth2_overview.html#refresh_token[refresh tokens] to obtain new access tokens.

NOTE: AM provides an extensibility mechanism for defining additional types. See link:/am/current/am_userguide_extension_grants.html[Extension grants] section.

NOTE: The use of one of these grant types will mainly depend of your application type.

=== Authorization Code

The authorization code is used by applications to obtain a temporary code after requesting the authorization of the End-User.

1. The End-User clicks *Sign in* within its application.
2. The End-User is redirected to the AM Authorization Server */oauth/authorize?response_type=code*.
3. The End-User authenticates using one of the configured identity providers and login options (MFA for example).
4. Optional. A consent page can be displayed to ask for user approvals.
5. AM redirects the End-User back to the application with an authorization code.
6. The application call the AM Authorization Server */oauth/token* to exchange the code for an access token (and optionally, a refresh token)
7. The application can use this access token to make secured API calls about the End-User.

NOTE: The authorization code is one use only.

NOTE: Flow used for web apps (server side). For native (mobile) and Javascript apps, you should also use the link:https://tools.ietf.org/html/rfc7636[PKCE extension], which provides protections against other attacks where the authorization code may be intercepted.

NOTE: Authorization Code grant URL : GET https://am-gateway/{domain}/oauth/authorize?response_type=code&client_id=web-app&redirect_uri=https://web-app/callback

NOTE: For more information about this flow, please read the link:https://tools.ietf.org/html/rfc6749#section-1.3.1[RFC].

=== Implicit

WARNING: OAuth standard now discourages the use of Implicit grant to request access tokens from Javascript applications.
You should considered using the link:/am/current/am_devguide_protocols_oauth2_overview.html#authorization_code[Authorization code] grant with PKCE extension for all your applications.

The implicit grant is a simplified authorization code flow. Instead of getting a temporary code first, you can retrieve an access token directly from the web browser redirection.

1. The End-User clicks *Sign in* within its application.
2. The End-User is redirected to the AM Authorization Server */oauth/authorize?response_type=token*.
3. The End-User authenticates using one of the configured identity providers and login options (MFA for example).
4. Optional. A consent page can be displayed to ask for user approvals.
5. AM redirects the End-User back to the application with an access token.
6. The application can use this access token to make secured API calls about the End-User.

NOTE: Implicit grant URL : GET https://am-gateway/{domain}/oauth/authorize?response_type=token&client_id=web-app&redirect_uri=https://web-app/callback

NOTE: For more information about this flow, please read the link:https://tools.ietf.org/html/rfc6749#section-1.3.2[RFC].

=== Resource owner password credentials

The resource owner password credentials (i.e. username and password) can be used directly as an authorization grant to obtain an access token (in REST manner).

The biggest difference with the others flows is that the authentication process is triggered by the application and not the AM Authorization Server.

NOTE: Should only be used when there is a high degree of trust between the resource owner and the client (e.g., the client is part of the device operating system or a highly privileged application), and when other authorization grant types are not available (such as the authorization code).

1. The End-User clicks *Sign in* and enters its credentials (username/password) in the application form.
2. The application forward the credentials to the AM Authorization Server */oauth/token*.
3. AM check the credentials.
4. AM responds with an access token (and optionally, a refresh Token).
5. The application can use this access token to make secured API calls about the End-User.

NOTE: Resource Owner Password Credentials grant URL : POST https://am-gateway/{domain}/oauth/token?grant_type=password&username=john&password=doe (with Basic client credentials)

NOTE: For more information about this flow, please read the link:https://tools.ietf.org/html/rfc6749#section-1.3.3[RFC].

=== Client credentials

The Client Credentials grant type is used by clients to obtain an access token outside of the context of a user.
This is typically used by clients to access resources about themselves rather than to access a user's resources.

NOTE: Flow used typically when the client is acting on its own behalf (the client is also the resource owner). Machine to machine communication

NOTE: Client Credentials grant URL : POST https://am-gateway/{domain}/oauth/token?grant_type=client_credentials (with Basic client credentials)

NOTE: For more information about this flow, please read the link:https://tools.ietf.org/html/rfc6749#section-1.3.4[RFC].

=== Refresh token

A refresh token is used to get a new access token letting client application to renew access to protected resources without prompting login page to the resource owner.

NOTE: The refresh token is one use only.

NOTE: For security reason (a user can remain authenticated forever), a refresh token must be stored in secure place (i.e server side).

NOTE: Refresh token grant URL : POST https://am-gateway/{domain}/oauth/token?grant_type=refresh_token&refresh_token={refreshToken} (with Basic client credentials)

== Endpoints

As per of the specification, AM provides the following endpoints :

=== Authorization endpoint

link:https://tools.ietf.org/html/rfc6749#section-3.1[The authorization endpoint] is used to interact with the resource owner and obtain an authorization grant.
The authorization server MUST first verify the identity of the resource owner.

NOTE: Authorization endpoint URL : https://am-gateway/{domain}/oauth/authorize

=== Token endpoint

link:https://tools.ietf.org/html/rfc6749#section-3.2[The token endpoint] is used by the client to obtain an access token by presenting its authorization grant or refresh token.

NOTE: Authorization endpoint URL : https://am-gateway/{domain}/oauth/token

=== Introspection endpoint

link:https://tools.ietf.org/html/rfc7662#section-2[The introspection endpoint] is an OAuth 2.0 endpoint that takes a parameter representing an OAuth 2.0 token and returns a JSON [RFC7159] document representing the meta information surrounding the token, including whether this token is currently active.

NOTE: Introspection endpoint URL : https://am-gateway/{domain}/oauth/introspect

=== Revocation endpoint

link:https://tools.ietf.org/html/rfc7009[The revocation endpoint] is an OAuth 2.0 endpoint which allows clients to notify the authorization server that a previously obtained refresh or access token is no longer needed.

NOTE: Revocation endpoint URL : https://am-gateway/{domain}/oauth/revoke

== Example

Let's imagine that a user wants to access his personal data via a web application. The personal data is exposed through an API secured by the OAuth 2.0 protocol.

. The user must be logged in to access his data. The user requests the web application to sign in.
. The web application sends an Authorization Request (resource owner ask to grant access to his data) to the Authorization Server.
+
[source]
----
GET  https://am-gateway/{domain}/oauth/authorize?response=code&client_id=web-app&redirect_uri=https://web-app/callback&state=6789DSKL HTTP/1.1
----
+
. The authorization server authenticates the resource owner and obtains authorization
+
[source]
----
HTTP/1.1 302 Found
Location: https://am-gateway/{domain}/login?client_id=web-app

Login page with username/password form
----
+
[source]
----
HTTP/1.1 302 Found
Location: https://am-gateway/{domain}/oauth/confirm_access

Consent resource owner page. The resource owner accepts or denies permission for the web application to access the resource owner's personal data
----
+
[source]
----
HTTP/1.1 302 Found
Location: https://web-app/callback?code=js89p2x1&state=6789DSKL

Come back to the web application
----
+
. The resource owner is authenticated and approved web application acting on the resource owner's behalf. The web application can ask for an access token.
+
[source]
----
POST https://am-gateway/{domain}/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
grant_type=authorization_code&code=6789DSKL&redirect_uri=https://web-app/callback&state=6789DSKL
----
+
[source]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
{
    "access_token": "b02063f8-2698-4141-a063-f82698e1419c",
    "token_type": "bearer",
    "expires_in": 7199,
    "scope": "read",
    "refresh_token": "4f85e0ad-b5df-4717-85e0-adb5dfc7174d"
}
----
+
. The web application has obtained an access token, which it can use to get the user's personal data.
+
[source]
----
GET  https://api.company.com/users/@me
Authorization: Bearer b02063f8-2698-4141-a063-f82698e1419c
----
+
. The Users API must check the incoming token to determine the active state of the access token and decide whether to accept or deny the request.
+
[source]
----
POST https://am-gateway/{domain}/oauth/introspect HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
token=b02063f8-2698-4141-a063-f82698e1419c

Introspection request
----
+
[source]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "active": true,
  "client_id": "web-app",
  "username": "jdoe",
  "sub": "Z5O3upPC88QrAjx00dis",
  "aud": "https://web-app",
  "iss": "https://am-gateway/",
  "exp": 1419356238,
  "iat": 1419350238
}

Introspection response
----
+
[source]
----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "username": "jdoe",
  "family_name": "doe",
  "name": "John doe",
  "email": "jdoe@mail.com"
}

Users API response
----
+
. The access is valid and the web application can display the resource owner's personal data.

. If the resource owner decides to log out, the web application can ask the Authorization Server to revoke the active access token.
+
[source]
----
POST https://am-gateway/{domain}/oauth/revoke HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
token=b02063f8-2698-4141-a063-f82698e1419c

Revocation request
----
+
[source]
----
HTTP/1.1 200 OK

Revocation response
----
